# ansible-galaxy collection install community.windows
#
- name: change PasswordComplexity
  community.windows.win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 0

- name: change MaximumPasswordAge (パスワードの有効期限)
  community.windows.win_security_policy:
    section: System Access
    key: MaximumPasswordAge
    value: -1

