---
- name: copy create password Policy ps1
  template:
    src: files/AD-PasswordPolicy.ps1.j2
    dest: c:\AD-PasswordPolicy.ps1

- name: Run create password Policy ps1
  win_shell: powershell.exe  -ExecutionPolicy ByPass -File "C:\AD-PasswordPolicy.ps1" >> "C:\AD-PasswordPolicy.ps1.logs.txt"

  
