---
- name: facts ec2 instances
  ec2_instance_info:
    profile: "{{ aws_cli_profile | default(omit) }}"
    region: "{{ aws_region }}"
    filters:
      instance-state-name: ['running']
  register: _ec2_instance_facts

- name: facts ec2 ami
  ec2_ami_info:
    profile: "{{ aws_cli_profile | default(omit) }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ item.ami_name }}"
  with_items: "{{ target_instance }}"
  register: ec2_ami_info_result

- name: create AMI
  ec2_ami:
    profile: "{{ aws_cli_profile | default(omit) }}"
    region: "{{ aws_region }}"
    instance_id: "{{ item.instance_id }}"
    wait: yes
    wait_timeout: 1500
    name: "{{ item.ami_name }}"
    state: present
    delete_snapshot: true
    tags:
      Name: "{{ item.ami_name }}"
  with_items: "{{ target_instance }}"
  register: ec2_ami
  when: ec2_ami_info_result.results[0].images[0].image_id is not defined

- name: re-fact ec2 ami
  ec2_ami_info:
    profile: "{{ aws_cli_profile | default(omit) }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ item.ami_name }}"
  with_items: "{{ target_instance }}"
  register: ec2_ami_info_result

