---
- name: get server password
  uri:
    url: "https://compute.{{ os_region_name }}.cloud.global.fujitsu.com/v2.1/{{ os_project_id }}/servers/{{ server_id }}/os-server-password"
    method: GET
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      X-Auth-Token: "{{ x_auth_token }}"
    status_code: 200
  register: get_server_password
  until: get_server_password | json_query('json.password')
  retries: 100
  delay: 10
# - debug: 
#     var: get_server_password

- set_fact:
    server_password: "{{ get_server_password | json_query('json.password') }}"
- debug:
    var: server_password

- name: decode server password
# shell: echo {{ server_password }} | openssl base64 -d -A | openssl rsautl -decrypt -inkey "./files/{{ public_key_name}}.pem"
  shell: echo {{ get_server_password | json_query('json.password') }} | openssl base64 -d -A | openssl rsautl -decrypt -inkey "./files/{{ public_key_name}}.pem"
  register: decode_password
    
- debug:
    var: decode_password.stdout_lines

