---
- name: facts subnet
  ec2_vpc_subnet_info:
    profile: "{{ aws_cli_profile | default(omit) }}"
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ aws_vpc.vpc.id }}"
  register: _subnet_facts

- name: facts ec2 instances
  ec2_instance_info:
    profile: "{{ aws_cli_profile | default(omit) }}"
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ aws_vpc.vpc.id }}"
      instance-state-name: ['running']
  register: _ec2_instance_facts


- name: create ENI
  ec2_eni:
    profile: "{{ aws_cli_profile | default(omit) }}"
    region: "{{ aws_region }}"
    private_ip_address: "{{ item.secondary_private_ip }}"
    subnet_id: "{{ _subnet_facts.subnets | selectattr('tags.Name', 'defined') | selectattr('tags.Name', 'equalto', item.secondary_subnet_name) | map(attribute='id') | first }}"
    instance_id: "{{ _ec2_instance_facts.instances | selectattr('tags.Name', 'defined') | selectattr('tags.Name', 'equalto', item.name) | map(attribute='instance_id') | first }}"
    device_index: "{{ item.secondary_eni_dev_index }}"
    attached: true
    delete_on_termination: true
    state: present
  with_items: "{{ ec2 }}"
  when: item.secondary_private_ip is defined

