---
- name: copy LifeKeeper install iso image
  copy:
    src: "files/{{ lifekeeper_iso_file }}"
    dest: "~/{{ lifekeeper_iso_file }}"

- name: copy LifeKeeper license file
  copy:
    src: "files/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
   - "{{ license_file }}"

- name: copy LifeKeeper installer conf file
  template:
    src: "lifekeeper_installer.conf.j2"
    dest: "~/lifekeeper_installer.conf"
  register: lk_installer_config_change

- name: copy LifeKeeper setup file
  shell: >
    mount -o loop ~/{{ lifekeeper_iso_file }} /media;
    mount -o loop /media/sps_*.img /mnt;
    mkdir -p ~/sps_installer;
    cp -r /mnt/* ~/sps_installer/;
    umount /mnt;
    umount /media;
  args:
    creates: ~/sps_installer/setup

