---
# ----------------------------------------
# OS Settings
# ----------------------------------------
selinux_state: disabled
datakeeper_partition:
 - device: /dev/vdb1
   number: 1
   label: gpt
   fstype: xfs
   state: present
swap_file_path: /swapfile
swap_file_size_mb: '4096'
swap_file_state: present
swap_file_create_command: "dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_file_size_mb }}"

