---
- name: add /etc/sysconfig/network-scripts/ifcfg-eth1
  blockinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    create: yes
    content: |
      BOOTPROTO=dhcp
      DEVICE=eth1
      ONBOOT=yes
      TYPE=Ethernet
      USERCTL=no
      DEFROUTE=no

- name: ifup eth1
  shell: ifup eth1
  ignore_errors: true


