---
- name: install lifekeeper
  shell: script -q -e -c "~/sps_installer/setup -f ~/{{ lifekeeper_setup_conf_file }} -q y" ~/lifekeeper_install.log
  args:
    creates: /opt/LifeKeeper/bin/lkstart
  register: lifekeeper_install_result
  ignore_errors: true

#- name: debug
#  debug: var=lifekeeper_install_result

#- name: print_msg
#  debug:
#    msg: "{{ item }}"
#  with_items:
#   - "Currentry lifekeeper installer not work."
#   - "Please run 'sps_installer/setup' manualy."
#   - "# ~/sps_installer/setup -q y -f ~/{{ lifekeeper_setup_conf_file }}"
#  when: lifekeeper_install_result.rc != 0

#- name: wait LifeKeeper install
#  pause:
#    prompt: "Please install LifeKeeper manualy, if press Enter key to continue."
#  when: lifekeeper_install_result.rc != 0

- name: lkstart
  shell: /opt/LifeKeeper/bin/lkstart

- name: check lifekeeper license installed
  shell: ls /var/LifeKeeper/license/*
  register: check_lisense_file
  failed_when: false

#- name: debug
#  debug: var=check_lisense_file

- name: install lifekeeper license
  shell: /opt/LifeKeeper/bin/lkkeyins ~/{{ lifekeeper_license_file }}
  when: check_lisense_file.rc == 2

