---
- name: installer config changed check
  file:
    path: /root/lifekeeper-install.DONE
    state: absent
  when: lk_installer_config_change.changed

- name: install lifekeeper
  shell: script -q -e -c "~/sps_installer/setup -f ~/lifekeeper_installer.conf -q y" ~/lifekeeper_install.log
  args:
    creates: /root/lifekeeper-install.DONE
  register: lifekeeper_install_result

- name: lifekeeper install check
  file:
    path: /root/lifekeeper-install.DONE
    state: touch
  when: lifekeeper_install_result.rc == 0

- name: lkstart
  shell: /opt/LifeKeeper/bin/lkstart

- name: check lifekeeper license installed
  shell: ls /var/LifeKeeper/license/*
  register: check_lisense_file
  failed_when: false

- name: install lifekeeper license
  shell: /opt/LifeKeeper/bin/lkkeyins ~/{{ lifekeeper_license_file }}
  when: check_lisense_file.rc == 2
 
- name: add PATH, MANPATH to /root/.bash_profile
  lineinfile:
    dest: /root/.bash_profile
    line: "{{ item }}"
  with_items:
    - 'PATH=$PATH:/opt/LifeKeeper/bin'
    - 'MANPATH=$MANPATH:/opt/LifeKeeper/man'
    - 'export PATH MANPATH'

