---
- name: make .ssh dir
  become: yes
  become_user: "{{ target_user }}"
  file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: copy ssh key file to server
  become: yes
  become_user: "{{ target_user }}"
  copy:
    src: "{{ ansible_ssh_private_key_file }}"
    dest: "~/.ssh/id_rsa"
    mode: 0600

