---
- name: move mysql data dir to DataKeeper volume
  shell: mv "{{ mysql_rpm_data_dir }}" "{{ mysql_data_dir }}"
  args:
    creates: "{{ mysql_data_dir }}"

- name: create symlink to "{{ mysql_rpm_data_dir }}"
  file:
   src: "{{ mysql_data_dir }}"
   dest: "{{ mysql_rpm_data_dir }}"
   state: link

- name: create mysql data
  become: yes
  become_user: mysql
  shell: mysql_install_db
  args:
    creates: "{{ mysql_data_dir }}/mysql"

