---
- name: create firewall rule
  uri:
    url: https://networking.{{ os_region_name }}.cloud.global.fujitsu.com/v2.0/fw/firewall_rules
    method: POST
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      X-Auth-Token: "{{ x_auth_token }}"
    body_format: json
    body: "{{ lookup('template', 'firewall_rule.j2') }}"
    status_code: 201
  with_items: "{{ firewall_rules }}"
  register: response
  when:
    firewall_skip_flag == false
# - debug:
#     msg: "{{ response | json_query('results[*].json.firewall_rule.id') }}"

- set_fact:
    firewall_rule_ids: "{{ response | json_query('results[*].json.firewall_rule.id') }}"
  when:
    firewall_skip_flag == false

